import {expect,test} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

function apkBytes(size=0){const name=new TextEncoder().encode('AndroidManifest.xml'),body=new Uint8Array(size),bytes=new Uint8Array(30+name.length+body.length+46+name.length+22),view=new DataView(bytes.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(26,name.length,true);bytes.set(name,30);bytes.set(body,30+name.length);const cd=30+name.length+body.length;view.setUint32(cd,0x02014b50,true);view.setUint16(cd+28,name.length,true);bytes.set(name,cd+46);const eocd=cd+46+name.length;view.setUint32(eocd,0x06054b50,true);view.setUint16(eocd+8,1,true);view.setUint16(eocd+10,1,true);view.setUint32(eocd+12,46+name.length,true);view.setUint32(eocd+16,cd,true);return bytes}
async function chooseApk(page:any,name='Example',size=0){await page.getByRole('button',{name:/record an apk/i}).first().click();await page.locator('input[type=file]').setInputFiles({name:'evidence.apk',mimeType:'application/vnd.android.package-archive',buffer:Buffer.from(apkBytes(size))});await page.getByLabel('App name').fill(name);await page.getByLabel('Source URL').fill('https://example.test/apk');await page.getByRole('button',{name:/hash and record apk/i}).click();await expect(page.getByRole('button',{name:`Remove ${name}`})).toBeVisible()}

test('@claim:hash-check hashes selected APK bytes on this device',async({page})=>{await page.goto('/');await chooseApk(page);await expect(page.locator('.record p.mono')).toContainText('SHA-256')});
test('@claim:demo-sandbox keeps demo data and files separate from real records',async({page})=>{await page.goto('/demo');await expect(page.getByText('Demo — sample data, nothing is saved')).toBeVisible();await chooseApk(page,'Demo APK');await page.getByRole('link',{name:'Start for real'}).click();await page.waitForURL('/');const names=await page.evaluate(()=>new Promise<string[]>((resolve,reject)=>{const r=indexedDB.open('demo:apk-locker-files');r.onsuccess=()=>resolve(Array.from(r.result.objectStoreNames));r.onerror=()=>reject(r.error)}));expect(names).toEqual([]);await expect(page.getByText('No APK evidence yet')).toBeVisible()});
test('@claim:local-storage stores real records only in the real namespace',async({page})=>{await page.goto('/');await chooseApk(page,'Real APK');const namespaces=await page.evaluate(()=>Object.keys(localStorage).sort());expect(namespaces).toContain('apk-locker:records');expect(namespaces).not.toContain('demo:apk-locker:records');await page.getByRole('button',{name:'Remove Real APK'}).click();await expect(page.getByText('No APK evidence yet')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('apk-locker:records'))).toBe('[]')});
test('@claim:encrypted-export exports an encrypted kit with a representative 12 MB saved APK',async({page})=>{await page.goto('/');await chooseApk(page,'Large APK',12*1024*1024);await page.getByRole('button',{name:'Export restore kit'}).click();await page.getByLabel('Password',{exact:true}).fill('twelve characters');await page.getByLabel('Confirm password',{exact:true}).fill('twelve characters');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download encrypted kit'}).click();expect((await download).suggestedFilename()).toMatch(/\.locker$/);await expect(page.locator('dialog')).toHaveCount(0)});
test('@claim:apk-structure rejects non-APK bytes',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/record an apk/i}).first().click();await page.locator('input[type=file]').setInputFiles({name:'broken.apk',mimeType:'application/vnd.android.package-archive',buffer:Buffer.from('not an apk')});await page.getByLabel('App name').fill('Broken');await page.getByRole('button',{name:/hash and record apk/i}).click();await expect(page.getByText(/not a ZIP-based APK|too short to be an APK/)).toBeVisible()});
test('passes axe on product routes and fits a 390px screen',async({page})=>{await page.setViewportSize({width:390,height:844});for(const path of ['/','/demo','/privacy','/terms']){await page.goto(path);expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)}for(const target of await page.locator('nav a, .demo-banner a, .demo-banner button, footer a').all()){const box=await target.boundingBox();expect(box?.height||0).toBeGreaterThanOrEqual(44)}});
test('@claim:offline-reload reloads the demo shell offline after the first visit',async({page,context})=>{await page.goto('/demo');await page.reload();await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBe(true);await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{level:1})).toHaveText('Keep APK restore evidence');await context.setOffline(false)});
