import './style.css';
import './plus.css';
import './contrast.css';
import { ApkRecord, Kit, assertApkArchive, b64, openKit, sampleRecords, sealKit, sha256, shortHash, unb64 } from './lib';
import {assessCompatibility,extractApkIdentity,verifyApk} from './apk';

const root=document.querySelector<HTMLDivElement>('#app')!;
const isDemo=()=>location.pathname==='/demo'||new URLSearchParams(location.search).get('demo')==='1';
const key=isDemo()?'demo:apk-locker:records':'apk-locker:records';
const productSlug='apk-provenance-locker';
const billingApi='https://api.sociobot.in/api/v1';
const licenseKey=`${isDemo()?'demo:':''}sb_license:${productSlug}`;
const verdictKey=`${licenseKey}:verdict`;
const licenseDay=86_400_000;
type CachedVerdict={valid:boolean;checkedAt:number};
let returnedLicense='';
{
  const url=new URL(location.href);
  returnedLicense=url.searchParams.get('license')?.trim()||'';
  if(returnedLicense){
    localStorage.setItem(licenseKey,returnedLicense);
    url.searchParams.delete('license');
    history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`);
  }
}
function cachedVerdict():CachedVerdict|null{try{return JSON.parse(localStorage.getItem(verdictKey)||'null')}catch{return null}}
const initialVerdict=cachedVerdict();
let licenseActive=Boolean(returnedLicense||initialVerdict?.valid);
let licenseStatus=licenseActive?'Locker Plus is active on this device.':isDemo()?'Demo uses isolated Locker Plus storage.':'The free locker is active.';
let records:ApkRecord[]=load(); let notice=''; let currentRoute=route(); let updateAvailable=false;
function load(){try{return (JSON.parse(localStorage.getItem(key)||'[]') as Array<ApkRecord&{name?:string;version?:string;signer?:string}>).map(record=>record.packageName?record:{...record,packageName:record.name||'Unknown package',versionCode:0,versionName:record.version||'unknown',currentSigner:record.signer||'',signers:[],lineage:[],verification:'legacy'} as ApkRecord)}catch{return []}}
function save(){localStorage.setItem(key,JSON.stringify(records));}
function route(){if(isDemo())return '/demo';return ['/','/privacy','/terms'].includes(location.pathname)?location.pathname:'/404'}
function esc(s:string){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!))}
function layout(content:string,title:string,description:string){document.title=title;document.querySelector('meta[name=description]')?.setAttribute('content',description);document.querySelector('meta[property="og:title"]')?.setAttribute('content',title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',description);document.querySelector('meta[name="twitter:title"]')?.setAttribute('content',title);document.querySelector('meta[name="twitter:description"]')?.setAttribute('content',description);document.querySelector<HTMLLinkElement>('link[rel=canonical]')?.setAttribute('href',`https://apk-provenance-locker.sociobot.in${currentRoute==='/'?'/':currentRoute}`);root.innerHTML=`
  <a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="/"><span>◆</span> APK Provenance Locker</a><nav aria-label="Main navigation"><a href="/demo">Demo</a><a href="/#locker">Locker</a><a href="/privacy" data-nav>Privacy</a></nav></header>
  ${isDemo()?'<aside class="demo-banner"><span aria-live="polite">Demo — sample data, nothing is saved</span><button data-reset>Reset demo</button><a href="/" data-real>Start for real</a></aside>':''}
  <main id="main" tabindex="-1">${content}</main><footer><span>Records and saved APK copies stay on this device.</span><a href="/privacy" data-nav>Privacy</a><a href="/terms" data-nav>Terms</a><span>Built by Param Factory · v0.5.5</span></footer><div class="toast" aria-live="polite">${esc(notice)}${updateAvailable?' An update is ready. <button data-update>Reload update</button>':''}</div>`;root.querySelector('h1')?.setAttribute('tabindex','-1');bind();}
function landing(){layout(`<section class="hero"><div class="hero-copy"><p class="eyebrow">Local APK verification</p><h1>Verify APKs before restoring</h1><p class="lede">For Android users keeping APK files, this checks each app, version, signing history, and SHA-256 file fingerprint before a reinstall.</p><div class="hero-actions"><a class="button primary" href="/?demo=1">Try it with sample data</a><span>Open two sample APK records.</span><button class="button paper" data-add>Verify an APK</button></div><ul class="facts"><li>Verified on this device</li><li>Password-encrypted exports</li><li>No sign-in or account</li></ul></div><figure><img src="/archive-locker.webp" width="1152" height="768" fetchpriority="high" decoding="async" alt="A paper-cut archive cabinet holding APK evidence parcels and certificate slips."/><figcaption>Your APK files are never uploaded.</figcaption></figure></section>${lockerSection()}<section class="how"><h2>How the locker verifies evidence</h2><ol><li><b>Choose an APK.</b><span>The locker checks Android's v1, v2, and v3 signatures and creates a SHA-256 file fingerprint on this device.</span></li><li><b>Read the package and version.</b><span>It extracts the package name and version code from the compiled Android manifest.</span></li><li><b>Check signer and downgrade risks.</b><span>Verified signing history and version codes reveal new certificates and incompatible downgrade risk.</span></li></ol></section>${licenseSection()}${downloadSection()}`,'APK Provenance Locker — Verify APK restore evidence','Verify APK signatures, identity, signing history, and SHA-256 file fingerprints on your device.');}
function demo(){layout(`<section class="demo-product"><p class="eyebrow">Sample data</p><h1>Check sample APK records</h1><p>These two sample records show the evidence the locker keeps before a reinstall.</p></section>${lockerSection()}<section class="how demo-how"><h2>Use the sample locker</h2><ol><li><b>Open a record.</b><span>Read the package, version, signing history, and file fingerprint.</span></li><li><b>Verify an APK.</b><span>Choose your own file to check it on this device.</span></li><li><b>Reset the sample.</b><span>Start again without changing your real records.</span></li></ol></section>${licenseSection()}${downloadSection()}`,'Demo — APK Provenance Locker','Try two sample APK records in an isolated locker.');}
function lockerSection(){return `<section id="locker" class="locker-section"><div class="section-head"><div><p class="eyebrow">Your verified APK records</p><h2>Keep verified APK evidence</h2></div><div class="actions"><button class="button paper" data-add>Verify an APK</button><button class="button ink" data-export ${records.length?'':'disabled'}>Export restore kit</button></div></div>${lockerHtml()}</section>`}
function downloadSection(){return `<section class="plain"><h2>Android download</h2><p>APK checks run on this device using Android's signature rules. Android still makes the final install decision.</p><div class="release-links" data-release><a class="download" href="https://github.com/B-Divyesh/sf-apk-provenance-locker/releases/download/v0.5.5/app-release.apk">Download APK from GitHub</a><a href="https://github.com/B-Divyesh/sf-apk-provenance-locker/releases/download/v0.5.5/app-release.aab">Download AAB from GitHub</a><a href="https://github.com/B-Divyesh/sf-apk-provenance-locker/releases/download/v0.5.5/SHA256SUMS">Download SHA256SUMS from GitHub</a></div><p class="checksum">Use the versioned SHA256SUMS file to check the APK's SHA-256 file fingerprint.</p><ol class="install-steps"><li>Download the APK and its SHA256SUMS file.</li><li>Compare the APK's SHA-256 file fingerprint with the matching line in SHA256SUMS.</li><li>Allow installs from your browser or file manager when Android asks.</li><li>Open the APK. Android shows the final install decision.</li></ol></section>`}
function licenseSection(){return `<section class="plus" id="plus" aria-labelledby="plus-heading"><div><p class="eyebrow">Optional one-time purchase</p><h2 id="plus-heading">Group APKs by device</h2><p>Locker Plus costs $12 once. It adds private device labels for sorting a large locker. Verification, signer and downgrade warnings, and restore-kit export stay free.</p></div><div class="plus-actions"><p class="license-state" aria-live="polite">${esc(licenseStatus)}</p>${licenseActive?'<button class="button paper" data-license-remove>Remove license from this device</button>':`<a class="button primary" href="${billingApi}/products/${productSlug}/checkout">Buy Locker Plus — $12</a><button class="button paper" data-license>Restore Locker Plus license</button>`}<small>Sociobot hosted checkout.</small></div></section>`}
function lockerHtml(){if(!records.length)return `<div class="empty"><div class="seal">⌁</div><h3>No APK evidence yet</h3><p>Verified APKs will appear here. Choose a file to check its signature and identity.</p><button class="button primary" data-add>Verify your first APK</button></div>`;return `<div class="inventory" aria-label="APK inventory">${records.map(r=>`<article class="record"><div class="app-mark">▣</div><div class="record-main"><h3>${esc(r.packageName)} <span>${esc(r.versionName)} (${r.versionCode})</span></h3><p>${esc(r.filename)} · ${Math.round(r.size/1024/1024*10)/10} MB · ${r.backup?'copy saved':'metadata only'}</p>${r.deviceLabel?`<p class="device-label">Device: ${esc(r.deviceLabel)}</p>`:''}<p class="mono">File fingerprint (SHA-256) ${shortHash(r.sha256)}</p>${r.risk?`<p class="risk">${esc(r.risk)}</p>`:''}<button class="text-button" data-details="${r.id}">View full evidence</button></div><div class="proof"><span class="verified">● ${r.verification==='verified'?`Signature verified · ${r.schemes.join(' + ')}`:r.verification==='sample'?'Demo sample evidence':'Legacy unverified record'}</span>${r.lineage.length>1?`<span>${r.lineage.length}-certificate signing history verified</span>`:''}<span class="mono">${r.currentSigner?shortHash(r.currentSigner):'signer unavailable'}</span></div><button class="icon-button" data-remove="${r.id}" aria-label="Remove ${esc(r.packageName)}">×</button></article>`).join('')}</div><div class="kit-tools"><button class="button paper" data-validate>Validate a restore kit</button><p>Recheck file fingerprints, signatures, package identity, and signing history from saved APK copies.</p></div>`}
function policy(kind:'privacy'|'terms'){const privacy=kind==='privacy';layout(`<article class="legal"><p class="eyebrow">${privacy?'Privacy':'Terms'}</p><h1>${privacy?'Your APK data stays local':'Use your own lawful APKs'}</h1>${privacy?'<p>The locker stores selected records and optional APK copies in this browser or installed app. Android system backup and device transfer are disabled for installed-app data. Signature checks, identity reading, and exports send no APK data or record content over the network.</p><p>There are no analytics, advertising, accounts, or automatic third-party requests for the free locker. Download links contact GitHub only after you choose one.</p><p>If you save a Locker Plus license, its token stays in localStorage. The app sends only that token to api.sociobot.in at most once daily for verification.</p><p>Restore kits use your password for local encryption. The locker never stores that password. After you confirm Remove, it erases the record and its saved copy. Leaving or resetting the demo erases its separate demo storage.</p>':'<p>APK Provenance Locker verifies APK signatures and extracts package identity on your device. Use it only with APKs you lawfully own or may keep.</p><p>It reports verified signing history and version-code risk. Android remains the final authority for installation policy.</p><p>Locker Plus costs $12 once and adds private device labels. Verification, signer and downgrade warnings, and restore-kit export stay free.</p><p>Locker Plus uses Sociobot\'s hosted checkout. A refunded or revoked license stops private device labels.</p><p>Keep your restore-kit password and copies safe. The software is provided as-is under the MIT License.</p>'}</article>`,`${privacy?'Privacy':'Terms'} — APK Provenance Locker`,privacy?'How local APK verification and encrypted restore kits work.':'Terms for APK Provenance Locker.');}
async function leaveDemo(destination:string){
  await clearDemoStorage();
  location.assign(destination);
}
function bind(){root.querySelectorAll<HTMLAnchorElement>('a[href^="/"]:not([data-real])').forEach(a=>a.addEventListener('click',async event=>{if(!isDemo())return;const target=new URL(a.href,location.origin);if(target.pathname==='/demo'||target.searchParams.get('demo')==='1')return;event.preventDefault();try{await leaveDemo(`${target.pathname}${target.search}${target.hash}`)}catch{notice='Demo data could not be erased. Close other locker tabs, then try again.';render()}}));root.querySelectorAll<HTMLElement>('[data-nav]').forEach(a=>a.addEventListener('click',e=>{if(e.defaultPrevented)return;const href=(a as HTMLAnchorElement).getAttribute('href')!;if(href.startsWith('/')){e.preventDefault();history.pushState({},'',href);render(true);}}));root.querySelectorAll('[data-add]').forEach(x=>x.addEventListener('click',showAdd));root.querySelector('[data-export]')?.addEventListener('click',exportKit);root.querySelector('[data-validate]')?.addEventListener('click',validateKit);root.querySelector('[data-license]')?.addEventListener('click',restoreLicense);root.querySelector('[data-license-remove]')?.addEventListener('click',removeLicense);root.querySelector('[data-update]')?.addEventListener('click',()=>location.reload());root.querySelector('[data-reset]')?.addEventListener('click',async()=>{await clearDemoStorage();records=sampleRecords();save();licenseActive=false;licenseStatus='Demo uses isolated Locker Plus storage.';notice='Demo reset and its saved copies were erased.';render()});root.querySelector('[data-real]')?.addEventListener('click',async event=>{event.preventDefault();try{await leaveDemo('/')}catch{notice='Demo data could not be erased. Close other locker tabs, then try again.';render()}});root.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.addEventListener('click',()=>{const record=records.find(r=>r.id===b.dataset.remove);if(record)confirmRemove(record)}));root.querySelectorAll<HTMLButtonElement>('[data-details]').forEach(b=>b.addEventListener('click',()=>showDetails(records.find(r=>r.id===b.dataset.details)!)));}
function render(focusHeading=false){currentRoute=route();if(isDemo()&&!records.length){records=sampleRecords();save()}if(currentRoute==='/privacy')policy('privacy');else if(currentRoute==='/terms')policy('terms');else if(currentRoute==='/404')notFound();else if(currentRoute==='/demo')demo();else landing();if(focusHeading)requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}));}
function notFound(){layout('<article class="legal"><p class="eyebrow">Not found</p><h1>That page is not here</h1><p>Return to the APK locker to record or check your evidence.</p><a class="button primary" href="/" data-nav>Go to the locker</a></article>','Page not found — APK Provenance Locker','Return to APK Provenance Locker.');}
function dialog(inner:string){const d=document.createElement('dialog');d.className='dialog';d.innerHTML=inner;document.body.append(d);d.showModal();d.querySelector<HTMLElement>('[autofocus]')?.focus();d.addEventListener('close',()=>d.remove());return d}
function showAdd(){const d=dialog(`<form method="dialog" class="form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">New evidence slip</p><h2>Verify an APK you own</h2><label>APK file<input name="file" type="file" accept=".apk,application/vnd.android.package-archive" required autofocus></label><label>Source URL <input name="source" type="url" placeholder="https://…"></label><label class="check"><input name="backup" type="checkbox" checked> Save this APK copy in this browser</label><p class="small">The locker verifies v1, v2, and v3 signatures and lineage, then reads the package name and version code.</p><p class="form-error" aria-live="assertive"></p><button class="button primary" value="default">Verify and record APK</button></form>`);const form=d.querySelector('form')!;form.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(form),file=data.get('file') as File;if(!file)return;const button=form.querySelector<HTMLButtonElement>('.primary')!,err=form.querySelector('.form-error')!;button.disabled=true;button.textContent='Verifying APK…';try{const raw=await file.arrayBuffer();assertApkArchive(raw);const [hash,identity,proof]=await Promise.all([sha256(raw),extractApkIdentity(raw),verifyApk(raw)]);const compatibility=assessCompatibility({...identity,currentSigner:proof.currentSigner,lineage:proof.lineage},records.filter(r=>r.verification==='verified'));const risk=compatibility.kind==='downgrade'||compatibility.kind==='signer-change'?compatibility.message:undefined;const r:ApkRecord={id:crypto.randomUUID(),...identity,source:String(data.get('source')).trim()||'source not recorded',filename:file.name,size:file.size,sha256:hash,currentSigner:proof.currentSigner,signers:proof.signers,lineage:proof.lineage,schemes:proof.schemes,added:new Date().toISOString(),backup:data.get('backup')==='on',verification:'verified',risk};records.unshift(r);save();if(r.backup)await filePut(r.id,raw);notice=risk||`Verified ${identity.packageName}. ${compatibility.message}`;d.close();render()}catch(x){err.textContent=x instanceof Error?x.message:'The APK could not be verified. Choose a complete signed APK and try again.';button.disabled=false;button.textContent='Verify and record APK'}})}
async function exportKit(){const d=dialog(`<form method="dialog" class="form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Encrypted handoff</p><h2>Export a restore kit</h2><label>Password <input name="password" type="password" minlength="12" required autofocus aria-describedby="password-help"></label><p id="password-help" class="small">Use 12 or more characters. The password is not saved and cannot be recovered.</p><label>Confirm password <input name="confirm" type="password" minlength="12" required></label><p class="form-error" aria-live="assertive"></p><button class="button primary">Download encrypted kit</button></form>`);d.querySelector('form')!.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),p=String(f.get('password'));const err=d.querySelector('.form-error')!,button=d.querySelector<HTMLButtonElement>('.primary')!;if(p!==f.get('confirm')){err.textContent='The two passwords do not match.';return}button.disabled=true;button.textContent='Encrypting restore kit…';try{const files:Record<string,string>={};for(const r of records)if(r.backup){const raw=await fileGet(r.id);if(raw)files[r.id]=b64(raw)}const kit:Kit={format:'apk-provenance-locker/1',created:new Date().toISOString(),records,files},saved=Object.keys(files).length;download(`apk-restore-${new Date().toISOString().slice(0,10)}.locker`,await sealKit(kit,p),'application/json');notice=`Exported ${records.length} record${records.length===1?'':'s'} and ${saved} saved APK cop${saved===1?'y':'ies'}.`;d.close();render()}catch{err.textContent='The restore kit could not be encrypted. Try exporting fewer saved copies.';button.disabled=false;button.textContent='Download encrypted kit'}})}
type KitCheck={r:ApkRecord;status:string};
const kitMatch='file fingerprint, signature, identity, and signer match';
async function validateKit(){const d=dialog(`<form method="dialog" class="form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Before you restore</p><h2>Validate a restore kit</h2><label>Encrypted kit <input name="kit" type="file" accept=".locker,application/json" required autofocus></label><label>Kit password <input name="password" type="password" required></label><p class="form-error" aria-live="assertive"></p><button class="button primary">Check APK evidence</button></form>`);d.querySelector('form')!.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),file=f.get('kit') as File,err=d.querySelector('.form-error')!,button=d.querySelector<HTMLButtonElement>('.primary')!;button.disabled=true;button.textContent='Checking APK evidence…';try{const kit=await openKit(await file.text(),String(f.get('password')));const checks=await Promise.all(kit.records.map(async r=>{const encoded=kit.files[r.id];if(!encoded)return {r,status:'saved APK copy missing'};try{const raw=unb64(encoded),actual=await sha256(raw);if(actual!==r.sha256)return {r,status:'FILE FINGERPRINT MISMATCH'};const [proof,identity]=await Promise.all([verifyApk(raw),extractApkIdentity(raw)]);if(identity.packageName!==r.packageName||identity.versionCode!==r.versionCode)return {r,status:'PACKAGE OR VERSION MISMATCH'};if(proof.currentSigner!==r.currentSigner)return {r,status:'SIGNER MISMATCH'};return {r,status:kitMatch}}catch{return {r,status:'SIGNATURE INVALID'}}}));d.close();showResults(kit,checks)}catch(x){err.textContent=x instanceof Error?x.message:'The kit could not be opened.';button.disabled=false;button.textContent='Check APK evidence'}})}
function showResults(kit:Kit,checks:KitCheck[]){const matching=checks.filter(x=>x.status===kitMatch),summary=matching.length===1?'1 APK matches':`${matching.length} APKs match`;const d=dialog(`<form method="dialog" class="form results"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Validation report</p><h2>${summary}</h2><p>Created ${new Date(kit.created).toLocaleDateString()}. Matching saved copies are ready to import or download.</p><ul>${checks.map(x=>`<li class="${x.status===kitMatch?'ok':'warn'}"><b>${esc(x.r.packageName)}</b><span>${esc(x.status)} · ${x.r.schemes.join('+')||'signature evidence unavailable'}</span>${x.status===kitMatch?`<button class="text-button" type="button" data-download-copy="${esc(x.r.id)}">Download verified APK</button>`:''}</li>`).join('')}</ul>${matching.length?'<button class="button paper" type="button" data-import-kit>Import verified records</button>':''}<button class="button primary">Close report</button></form>`);d.querySelectorAll<HTMLButtonElement>('[data-download-copy]').forEach(button=>button.addEventListener('click',()=>{const record=matching.find(x=>x.r.id===button.dataset.downloadCopy)?.r;if(record)downloadVerifiedCopy(kit,record)}));d.querySelector<HTMLButtonElement>('[data-import-kit]')?.addEventListener('click',()=>{d.close();showImport(kit,matching)})}
function downloadVerifiedCopy(kit:Kit,record:ApkRecord){const encoded=kit.files[record.id];if(!encoded)return;download(record.filename,unb64(encoded),'application/vnd.android.package-archive');notice=`Downloaded verified ${record.filename}.`;render()}
function showImport(kit:Kit,matching:KitCheck[]){const incoming=matching.map(x=>x.r);const conflicts=incoming.filter(source=>records.some(local=>local.packageName===source.packageName&&local.versionCode===source.versionCode));const d=dialog(`<form method="dialog" class="form results"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Restore verified evidence</p><h2>Import verified records</h2><p>${incoming.length} verified record${incoming.length===1?'':'s'} can be restored to this ${isDemo()?'demo':'locker'}.</p>${conflicts.length?`<p class="risk">${conflicts.length} record${conflicts.length===1?'':'s'} already ${conflicts.length===1?'uses':'use'} the same package and version.</p><p>Choose whether to keep those records or replace them with the verified kit copies.</p><div class="dialog-actions"><button class="button paper" type="button" data-import="keep">Import new records only</button><button class="button danger" type="button" data-import="replace">Replace matching records</button></div>`:'<button class="button primary" type="button" data-import="keep">Confirm import verified records</button>'}</form>`);d.querySelectorAll<HTMLButtonElement>('[data-import]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;await importVerifiedRecords(kit,incoming,button.dataset.import==='replace');d.close();render()}))}
async function importVerifiedRecords(kit:Kit,incoming:ApkRecord[],replace:boolean){const conflicts=records.filter(local=>incoming.some(source=>source.packageName===local.packageName&&source.versionCode===local.versionCode));if(replace){for(const record of conflicts)await fileDelete(record.id);records=records.filter(record=>!conflicts.includes(record))}const accepted=incoming.filter(source=>replace||!conflicts.some(local=>local.packageName===source.packageName&&local.versionCode===source.versionCode));for(const source of accepted){const id=crypto.randomUUID(),copy={...source,id,added:new Date().toISOString(),backup:Boolean(kit.files[source.id])};records.unshift(copy);const encoded=kit.files[source.id];if(encoded)await filePut(id,unb64(encoded).buffer)}save();notice=accepted.length?`Imported ${accepted.length} verified record${accepted.length===1?'':'s'} into this ${isDemo()?'demo':'locker'}.`:'No new records were imported.'}
function download(name:string,data:BlobPart,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function dbName(){return isDemo()?'demo:apk-locker-files':'apk-locker-files'}
function db(){return new Promise<IDBDatabase>((ok,bad)=>{const r=indexedDB.open(dbName(),1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
async function filePut(id:string,data:ArrayBuffer){const d=await db();return new Promise<void>((ok,bad)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').put(data,id);tx.oncomplete=()=>{d.close();ok()};tx.onerror=()=>{d.close();bad(tx.error)}})}
async function fileGet(id:string){const d=await db();return new Promise<ArrayBuffer|undefined>((ok,bad)=>{let value:ArrayBuffer|undefined;const tx=d.transaction('files');const r=tx.objectStore('files').get(id);r.onsuccess=()=>{value=r.result};tx.oncomplete=()=>{d.close();ok(value)};tx.onerror=()=>{d.close();bad(tx.error)}})}
async function fileDelete(id:string){const d=await db();return new Promise<void>((ok,bad)=>{const tx=d.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=()=>{d.close();ok()};tx.onerror=()=>{d.close();bad(tx.error)}})}
function clearDatabase(name:string){return new Promise<void>((ok,bad)=>{const r=indexedDB.deleteDatabase(name);r.onsuccess=()=>ok();r.onerror=()=>bad(r.error);r.onblocked=()=>bad(new Error('Close other locker tabs, then reset the demo again.'))})}
function clearFiles(){return clearDatabase(dbName())}
function clearDemoStorage(){localStorage.removeItem('demo:apk-locker:records');localStorage.removeItem(`demo:sb_license:${productSlug}`);localStorage.removeItem(`demo:sb_license:${productSlug}:verdict`);return clearDatabase('demo:apk-locker-files')}
function confirmRemove(r:ApkRecord){const contents=r.backup?'this record and its saved APK copy':'this record';const d=dialog(`<form method="dialog" class="form results"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Remove evidence</p><h2>Remove ${esc(r.packageName)}?</h2><p>This permanently erases ${contents} from this device. It cannot be undone.</p><p class="small">File: ${esc(r.filename)} · file fingerprint (SHA-256) ${esc(shortHash(r.sha256))}</p><div class="dialog-actions"><button class="button paper" value="cancel">Keep record</button><button class="button danger" type="button" data-confirm-remove>Remove record</button></div></form>`);d.querySelector<HTMLButtonElement>('[data-confirm-remove]')?.addEventListener('click',async()=>{await fileDelete(r.id);records=records.filter(record=>record.id!==r.id);save();notice=`Removed ${contents} from this device.`;d.close();render()})}
function showDetails(r:ApkRecord){const d=dialog(`<form method="dialog" class="form results"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Recorded evidence</p><h2>${esc(r.packageName)}</h2>${r.risk?`<p class="risk">${esc(r.risk)}</p>`:''}<dl class="evidence"><dt>Package from APK</dt><dd>${esc(r.packageName)}</dd><dt>Version from APK</dt><dd>${esc(r.versionName)} · code ${r.versionCode}</dd><dt>File</dt><dd>${esc(r.filename)}</dd><dt>Source</dt><dd>${r.source.startsWith('http')?`<a href="${esc(r.source)}" target="_blank" rel="noreferrer">${esc(r.source)}</a>`:esc(r.source)}</dd><dt>File fingerprint (SHA-256)</dt><dd class="mono">${esc(r.sha256)}</dd><dt>Current signer certificate</dt><dd class="mono">${esc(r.currentSigner||'not available')}</dd><dt>Verified signature schemes</dt><dd>${esc(r.schemes.join(' + ')||'none')}</dd><dt>Verified signing history</dt><dd>${r.lineage.length?r.lineage.map((node,index)=>`${index+1}. ${esc(node.subject)} — ${shortHash(node.certificateSha256)}`).join('<br>'):'No signing-key changes in this APK'}</dd><dt>Device label</dt><dd>${esc(r.deviceLabel||'No device label')}</dd></dl>${licenseActive?'<button class="button paper" type="button" data-device-label>Edit device label</button>':'<p class="small">Locker Plus adds private device labels. Verification, signer and downgrade warnings, and restore-kit export stay free.</p>'}<p class="small">${r.verification==='verified'?'The APK signature, signed identity, and included signing history were verified locally.':r.verification==='sample'?'This is sample metadata for the isolated demo. Choose your own APK for cryptographic verification.':'This record predates signature verification. Verify the APK again before restoring it.'}</p><button class="button primary">Close evidence</button></form>`);d.querySelector('[data-device-label]')?.addEventListener('click',()=>{d.close();showDeviceLabel(r)})}
function showDeviceLabel(r:ApkRecord){const d=dialog(`<form method="dialog" class="form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Locker Plus</p><h2>Label this APK by device</h2><label>Device label <input name="label" maxlength="60" value="${esc(r.deviceLabel||'')}" placeholder="For example: Pixel 8 backup" autofocus></label><p class="small">This label stays with the local record and its encrypted restore kit.</p><button class="button primary">Save device label</button></form>`);d.querySelector('form')!.addEventListener('submit',event=>{event.preventDefault();if(!licenseActive){d.close();return}r.deviceLabel=String(new FormData(event.currentTarget as HTMLFormElement).get('label')).trim()||undefined;save();notice=r.deviceLabel?'Device label saved locally.':'Device label removed.';d.close();render()})}
function restoreLicense(){const d=dialog(`<form method="dialog" class="form"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">Move your purchase</p><h2>Restore Locker Plus</h2><label>License token <input name="license" required autocomplete="off" autofocus aria-describedby="license-help"></label><p id="license-help" class="small">The token stays on this device and is sent only to Sociobot for verification.</p><p class="form-error" aria-live="assertive"></p><button class="button primary">Verify license</button></form>`);d.querySelector('form')!.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget as HTMLFormElement,token=String(new FormData(form).get('license')).trim(),button=form.querySelector<HTMLButtonElement>('.primary')!,error=form.querySelector<HTMLElement>('.form-error')!;if(!token)return;button.disabled=true;button.textContent='Checking license…';localStorage.setItem(licenseKey,token);localStorage.removeItem(verdictKey);licenseActive=false;const valid=await verifyLicense(token,false);if(valid){d.close();notice='Locker Plus is active on this device.';render();return}error.textContent=licenseStatus;button.disabled=false;button.textContent='Verify license'})}
function removeLicense(){localStorage.removeItem(licenseKey);localStorage.removeItem(verdictKey);licenseActive=false;licenseStatus='The license was removed. The free locker is still active.';render()}
async function verifyLicense(token:string,rerender=true){const prior=cachedVerdict();try{const response=await fetch(`${billingApi}/products/${productSlug}/verify?license=${encodeURIComponent(token)}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(response.status===429?'Too many checks. Wait a minute and try again.':'License verification is unavailable. Try again later.');const result=await response.json() as {valid:boolean;reason?:string};localStorage.setItem(verdictKey,JSON.stringify({valid:result.valid,checkedAt:Date.now()} satisfies CachedVerdict));licenseActive=result.valid;licenseStatus=result.valid?'Locker Plus is active on this device.':'This license is not active. Check the token or buy Locker Plus.';if(!result.valid)localStorage.removeItem(licenseKey);if(rerender)render();return result.valid}catch(error){licenseActive=Boolean(prior?.valid);licenseStatus=licenseActive?'Offline: using the last valid license check.':error instanceof Error?error.message:'License verification is unavailable. Try again later.';if(rerender)render();return undefined}}
function initializeLicense(){const token=returnedLicense||localStorage.getItem(licenseKey);if(!token)return;const cached=cachedVerdict();if(!returnedLicense&&cached?.checkedAt&&Date.now()-cached.checkedAt<licenseDay)return;void verifyLicense(token)}
window.addEventListener('popstate',()=>render(true));if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').then(registration=>{registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){updateAvailable=true;render()}})})}).catch(()=>{});if(!isDemo())void clearDemoStorage();render();initializeLicense();
